CREATE TABLE IF NOT EXISTS PRICES (
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID        BIGINT         NOT NULL,
    START_DATE      TIMESTAMP      NOT NULL,
    END_DATE        TIMESTAMP      NOT NULL,
    PRICE_LIST      INTEGER        NOT NULL,
    PRODUCT_ID      BIGINT         NOT NULL,
    PRIORITY        INTEGER        NOT NULL,
    PRICE           DECIMAL(10, 2) NOT NULL,
    CURR            CHAR(3)        NOT NULL,
    LAST_UPDATE     TIMESTAMP,
    LAST_UPDATE_BY  VARCHAR(50),
    CONSTRAINT CK_PRICES_DATES CHECK (END_DATE >= START_DATE)
);

CREATE INDEX IF NOT EXISTS IDX_PRICES_LOOKUP ON PRICES (BRAND_ID, PRODUCT_ID, START_DATE, END_DATE);
